/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pet;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       Scanner scanner = new Scanner(System.in);

        System.out.println("Welcome to Virtual Pet Game!");

        VirtualPet pet = new VirtualPet();

        while (true) {
            System.out.println("\nWhat would you like to do?");
            System.out.println("1. Pet the pet");
            System.out.println("2. Play with the pet");
            System.out.println("3. Feed the pet");
            System.out.println("4. Do nothing");
            System.out.println("5. Quit the game");

            int choice = scanner.nextInt();

            switch (choice) {
                case 1:
                    pet.pet();
                    break;
                case 2:
                    pet.play();
                    break;
                case 3:
                    pet.feed();
                    break;
                case 4:
                    pet.doNothing();
                    break;
                case 5:
                    System.out.println("Thank you for playing!");
                    System.exit(0);
                    break;
                default:
                    System.out.println("Invalid choice. Please try again.");
                    break;
            }
        }
    }
}
